// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwbJeLYcmi_EVoQjE5ypZQtAmJsHxAPkk',
    appId: '1:1014080045166:web:525f4f370b100f593ba67f',
    messagingSenderId: '1014080045166',
    projectId: 'flutteractivity-18084',
    authDomain: 'flutteractivity-18084.firebaseapp.com',
    databaseURL: 'https://flutteractivity-18084-default-rtdb.firebaseio.com',
    storageBucket: 'flutteractivity-18084.appspot.com',
    measurementId: 'G-BRVMBRQMM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQgfuJ2Xullo2MdIZoBP_B188nqOLB5VI',
    appId: '1:1014080045166:android:aba416546810f41f3ba67f',
    messagingSenderId: '1014080045166',
    projectId: 'flutteractivity-18084',
    databaseURL: 'https://flutteractivity-18084-default-rtdb.firebaseio.com',
    storageBucket: 'flutteractivity-18084.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL91MBVEjv81_E25gNAfm0IgDRESzdYzw',
    appId: '1:1014080045166:ios:f39455881e94a37f3ba67f',
    messagingSenderId: '1014080045166',
    projectId: 'flutteractivity-18084',
    databaseURL: 'https://flutteractivity-18084-default-rtdb.firebaseio.com',
    storageBucket: 'flutteractivity-18084.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL91MBVEjv81_E25gNAfm0IgDRESzdYzw',
    appId: '1:1014080045166:ios:f39455881e94a37f3ba67f',
    messagingSenderId: '1014080045166',
    projectId: 'flutteractivity-18084',
    databaseURL: 'https://flutteractivity-18084-default-rtdb.firebaseio.com',
    storageBucket: 'flutteractivity-18084.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwbJeLYcmi_EVoQjE5ypZQtAmJsHxAPkk',
    appId: '1:1014080045166:web:7822c4436ddd84283ba67f',
    messagingSenderId: '1014080045166',
    projectId: 'flutteractivity-18084',
    authDomain: 'flutteractivity-18084.firebaseapp.com',
    databaseURL: 'https://flutteractivity-18084-default-rtdb.firebaseio.com',
    storageBucket: 'flutteractivity-18084.appspot.com',
    measurementId: 'G-Q1DXLXT8PV',
  );

}